package com.lantianhcgp.readlater.data.repository

import com.lantianhcgp.readlater.agent.AgentOrchestrator
import com.lantianhcgp.readlater.data.db.dao.ArticleDao
import com.lantianhcgp.readlater.data.db.dao.TagDao
import com.lantianhcgp.readlater.data.db.entity.Article
import com.lantianhcgp.readlater.data.db.entity.ArticleTag
import com.lantianhcgp.readlater.data.db.entity.Tag
import com.lantianhcgp.readlater.data.model.ArticleStatus
import com.lantianhcgp.readlater.data.model.LlmConfig
import kotlinx.coroutines.flow.Flow
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ArticleRepository @Inject constructor(
    private val articleDao: ArticleDao,
    private val tagDao: TagDao,
    private val agentOrchestrator: AgentOrchestrator
) {

    fun getAllArticles(): Flow<List<Article>> = articleDao.getAllArticles()

    fun getArticlesByStatus(status: ArticleStatus): Flow<List<Article>> =
        articleDao.getArticlesByStatus(status)

    fun getFavoriteArticles(): Flow<List<Article>> = articleDao.getFavoriteArticles()

    fun searchArticles(query: String): Flow<List<Article>> = articleDao.searchArticles(query)

    suspend fun getArticleById(articleId: String): Article? = articleDao.getArticleById(articleId)

    suspend fun addArticle(url: String): String {
        val article = Article(id = UUID.randomUUID().toString(), url = url)
        articleDao.insertArticle(article)
        return article.id
    }

    suspend fun processArticle(articleId: String, config: LlmConfig) {
        val article = articleDao.getArticleById(articleId) ?: return

        articleDao.updateStatus(articleId, ArticleStatus.PROCESSING)

        try {
            val result = agentOrchestrator.processUrl(article.url, config)

            if (result.error != null) {
                articleDao.updateStatus(articleId, ArticleStatus.ERROR)
                return
            }

            val now = System.currentTimeMillis()
            articleDao.updateArticle(
                article.copy(
                    title = result.title,
                    summary = result.summary,
                    plainText = result.plainText,
                    imageUrl = result.imageUrl,
                    sourceDomain = result.sourceDomain ?: "",
                    readingTimeMinutes = result.readingTimeMinutes,
                    status = ArticleStatus.READY,
                    updatedAt = now
                )
            )

            for (tagName in result.tags) {
                var tag = tagDao.getTagByName(tagName)
                if (tag == null) {
                    tag = Tag(id = UUID.randomUUID().toString(), name = tagName, isAutoGenerated = true)
                    tagDao.insertTag(tag)
                }
                tagDao.insertArticleTag(ArticleTag(articleId = articleId, tagId = tag.id))
            }
        } catch (e: Exception) {
            articleDao.updateStatus(articleId, ArticleStatus.ERROR)
        }
    }

    suspend fun toggleFavorite(articleId: String) {
        val article = articleDao.getArticleById(articleId) ?: return
        articleDao.updateFavorite(articleId, !article.isFavorite)
    }

    suspend fun deleteArticle(article: Article) {
        articleDao.deleteArticle(article)
    }
}
