package com.lantianhcgp.readlater.data.repository

import com.lantianhcgp.readlater.agent.AgentOrchestrator
import com.lantianhcgp.readlater.data.db.dao.ArticleDao
import com.lantianhcgp.readlater.data.db.dao.TagDao
import com.lantianhcgp.readlater.data.db.entity.Article
import com.lantianhcgp.readlater.data.db.entity.ArticleTag
import com.lantianhcgp.readlater.data.db.entity.Tag
import com.lantianhcgp.readlater.data.model.ArticleStatus
import com.lantianhcgp.readlater.data.model.LlmConfig
import com.lantianhcgp.readlater.util.Logger
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ArticleRepository @Inject constructor(
    private val articleDao: ArticleDao,
    private val tagDao: TagDao,
    private val agentOrchestrator: AgentOrchestrator
) {

    private val processScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    fun getAllArticles(): Flow<List<Article>> = articleDao.getAllArticles()

    fun getArticlesByStatus(status: ArticleStatus): Flow<List<Article>> =
        articleDao.getArticlesByStatus(status)

    fun getFavoriteArticles(): Flow<List<Article>> = articleDao.getFavoriteArticles()

    fun searchArticles(query: String): Flow<List<Article>> = articleDao.searchArticles(query)

    suspend fun getArticleById(articleId: String): Article? = articleDao.getArticleById(articleId)

    suspend fun addArticle(url: String): String {
        val article = Article(id = UUID.randomUUID().toString(), url = url)
        articleDao.insertArticle(article)
        return article.id
    }

    fun processArticle(articleId: String, config: LlmConfig) {
        processScope.launch {
            Logger.i("ArticleRepository", "开始后台处理文章: $articleId")
            val article = articleDao.getArticleById(articleId) ?: return@launch

            articleDao.updateStatus(articleId, ArticleStatus.PROCESSING)

            try {
                val result = agentOrchestrator.processUrl(article.url, config)

                if (result.error != null) {
                    Logger.e("ArticleRepository", "处理失败: ${result.error}")
                    articleDao.updateStatus(articleId, ArticleStatus.ERROR)
                    return@launch
                }

                val now = System.currentTimeMillis()
                articleDao.updateArticle(
                    article.copy(
                        title = result.title,
                        summary = result.summary,
                        plainText = result.plainText,
                        imageUrl = result.imageUrl,
                        sourceDomain = result.sourceDomain ?: "",
                        readingTimeMinutes = result.readingTimeMinutes,
                        status = ArticleStatus.READY,
                        updatedAt = now
                    )
                )

                for (tagName in result.tags) {
                    var tag = tagDao.getTagByName(tagName)
                    if (tag == null) {
                        tag = Tag(id = UUID.randomUUID().toString(), name = tagName, isAutoGenerated = true)
                        tagDao.insertTag(tag)
                    }
                    tagDao.insertArticleTag(ArticleTag(articleId = articleId, tagId = tag.id))
                }
                Logger.i("ArticleRepository", "文章处理完成: ${result.title}")
            } catch (e: Exception) {
                Logger.e("ArticleRepository", "处理出错: ${e.message}")
                articleDao.updateStatus(articleId, ArticleStatus.ERROR)
            }
        }
    }

    suspend fun toggleFavorite(articleId: String) {
        val article = articleDao.getArticleById(articleId) ?: return
        articleDao.updateFavorite(articleId, !article.isFavorite)
    }

    suspend fun deleteArticle(article: Article) {
        articleDao.deleteArticle(article)
    }
}
